### PR TITLE
If else -> switch - case

### PR DESCRIPTION
**Pull request by chupper100**

### CODE REVIEW

**Comment by chupper100** [comment]
You may noticed that there are changes to other lines, this is know to be caused by the Prettier - Code Formatting extension that I installed on VS Code.

**Comment by snvmk** [comment]
As I see, file became larger in size. Let me build to see will it be smaller when i esbuild it

**Comment by snvmk** [comment]
So, it is the same 3.8kb in size after build. And tbh i also use prettier :D look at .prettierrc.json

**Comment by snvmk** [comment]
Uh oh... idk why, but the repo i cloned from your fork doesnt seem to have this commit with your changes... okay, i just woke up, let me at least eat  😁

**Comment by chupper100** [comment]
Using switch - case performs better than using if - else since it is implemented by using an indexed branch table.

You may find out more information about it [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/switch).

**Comment by chupper100** [comment]
@snvmk

**Comment by snvmk** [comment]
okay lets try

**Comment by snvmk** [comment]
pretty nice, staying on it

**Pull request merged**
